### ISSUE TITLE
Risky backuppc exclude 

### ISSUE THREAD

**Issue by JoelLinn** [teamapps-org/ansible-collection-teamapps-general#4]
This will exclude a folder in the nextcloud folder `/container/nextcloud/nextcloud/lib/composer/composer/../../../lib/private/Cache/` which makes restores broken.
[  - 'Cache'](https://github.com/teamapps-org/ansible-collection-teamapps-general/blob/5caa7262cf46d0f1b2f469472f85166dfbdec9ec/roles/backuppc/defaults/main.yml#L42)

**Comment by JoelLinn** [comment]
Plus a lot of other paths that will be missing from backups

**Comment by pgassmann** [comment]
nextcloud lib and other cache paths are part of the software deployment. I don't think any user generated data in those paths need to be backed up.
